function [x,F,inform,xmul,Fmul,xstate,Fstate,output] = solve_snopt(start,stopFun,name,userfun,x, ...
						  xlow, xupp, xmul, xstate,...
						  Flow, Fupp, Fmul, Fstate,...
						  ObjAdd, ObjRow, ...
						  A, iAfun, jAvar, iGfun, ...
						  jGvar)
%function [x,F,inform,xmul,Fmul,xstate,Fstate,output] = solve_snopt(start,stopFun,name,userfun,x, ...
%						  xlow, xupp, xmul, xstate,...
%						  Flow, Fupp, Fmul, Fstate,...
%						  ObjAdd, ObjRow, ...
%						  A, iAfun, jAvar, iGfun, ...
%						  jGvar)
% Wrapper for solving NLPs

mexopt = 1;
[x,F,inform,xmul,Fmul, ...
 xstate,Fstate,itn,mjritn] = snoptmex(mexopt, ...
				      start, stopFun, name, ...
				      userfun, x, ...
				      xlow, xupp, xmul, xstate, ...
				      Flow, Fupp, Fmul, Fstate, ...
				      ObjAdd, ObjRow, ...
				      A, iAfun, jAvar, ...
				      iGfun, jGvar);

output.info       = inform;
output.iterations = itn;
output.majors     = mjritn;

